import type { CountryCurrencyLocale } from '@/types/country';

const countryCurrencyMapping: CountryCurrencyLocale[] = [
  { country: 'Afghanistan', currency: 'AFN', locale: 'fa-AF' },
  { country: 'Albania', currency: 'ALL', locale: 'sq-AL' },
  { country: 'Algeria', currency: 'DZD', locale: 'ar-DZ' },
  { country: 'Angola', currency: 'AOA', locale: 'pt-AO' },
  { country: 'Argentina', currency: 'ARS', locale: 'es-AR' },
  { country: 'Australia', currency: 'AUD', locale: 'en-AU' },
  { country: 'Austria', currency: 'EUR', locale: 'de-AT' },
  { country: 'Bangladesh', currency: 'BDT', locale: 'bn-BD' },
  { country: 'Belgium', currency: 'EUR', locale: 'nl-BE' },
  { country: 'Brazil', currency: 'BRL', locale: 'pt-BR' },
  { country: 'Canada', currency: 'CAD', locale: 'en-CA' },
  { country: 'Chile', currency: 'CLP', locale: 'es-CL' },
  { country: 'China', currency: 'CNY', locale: 'zh-CN' },
  { country: 'Colombia', currency: 'COP', locale: 'es-CO' },
  { country: 'Czech Republic', currency: 'CZK', locale: 'cs-CZ' },
  { country: 'Denmark', currency: 'DKK', locale: 'da-DK' },
  { country: 'Egypt', currency: 'EGP', locale: 'ar-EG' },
  { country: 'Ethiopia', currency: 'ETB', locale: 'am-ET' },
  { country: 'Finland', currency: 'EUR', locale: 'fi-FI' },
  { country: 'France', currency: 'EUR', locale: 'fr-FR' },
  { country: 'Germany', currency: 'EUR', locale: 'de-DE' },
  { country: 'Ghana', currency: 'GHS', locale: 'en-GH' },
  { country: 'India', currency: 'INR', locale: 'hi-IN' },
  { country: 'Indonesia', currency: 'IDR', locale: 'id-ID' },
  { country: 'Italy', currency: 'EUR', locale: 'it-IT' },
  { country: 'Japan', currency: 'JPY', locale: 'ja-JP' },
  { country: 'Kenya', currency: 'KES', locale: 'en-KE' },
  { country: 'Mexico', currency: 'MXN', locale: 'es-MX' },
  { country: 'Netherlands', currency: 'EUR', locale: 'nl-NL' },
  { country: 'New Zealand', currency: 'NZD', locale: 'en-NZ' },
  { country: 'Nigeria', currency: 'NGN', locale: 'en-NG' },
  { country: 'Norway', currency: 'NOK', locale: 'no-NO' },
  { country: 'Pakistan', currency: 'PKR', locale: 'ur-PK' },
  { country: 'Philippines', currency: 'PHP', locale: 'fil-PH' },
  { country: 'Poland', currency: 'PLN', locale: 'pl-PL' },
  { country: 'Russia', currency: 'RUB', locale: 'ru-RU' },
  { country: 'Saudi Arabia', currency: 'SAR', locale: 'ar-SA' },
  { country: 'South Africa', currency: 'ZAR', locale: 'en-ZA' },
  { country: 'South Korea', currency: 'KRW', locale: 'ko-KR' },
  { country: 'Spain', currency: 'EUR', locale: 'es-ES' },
  { country: 'Sweden', currency: 'SEK', locale: 'sv-SE' },
  { country: 'Switzerland', currency: 'CHF', locale: 'de-CH' },
  { country: 'Thailand', currency: 'THB', locale: 'th-TH' },
  { country: 'Turkey', currency: 'TRY', locale: 'tr-TR' },
  { country: 'United Arab Emirates', currency: 'AED', locale: 'ar-AE' },
  { country: 'United Kingdom', currency: 'GBP', locale: 'en-GB' },
  { country: 'United States', currency: 'USD', locale: 'en-US' },
  { country: 'Vietnam', currency: 'VND', locale: 'vi-VN' },
  { country: 'Zimbabwe', currency: 'ZWL', locale: 'en-ZW' },
];

export { countryCurrencyMapping };

export interface CountryCurrencyUIUsage {
  name: string; // Aligns with displayField
  value: string; // Aligns with valueField (Unique ISO Code)
  category: string; // Aligns with categorical pill badge (Region)
  country: string; // Retained original property
  currency: string; // Retained original property
  locale: string; // Retained original property
}

export const countries: CountryCurrencyUIUsage[] = [
  {
    name: 'Afghanistan',
    value: 'AF',
    category: 'Asia',
    country: 'Afghanistan',
    currency: 'AFN',
    locale: 'fa-AF',
  },
  {
    name: 'Albania',
    value: 'AL',
    category: 'Europe',
    country: 'Albania',
    currency: 'ALL',
    locale: 'sq-AL',
  },
  {
    name: 'Algeria',
    value: 'DZ',
    category: 'Africa',
    country: 'Algeria',
    currency: 'DZD',
    locale: 'ar-DZ',
  },
  {
    name: 'Angola',
    value: 'AO',
    category: 'Africa',
    country: 'Angola',
    currency: 'AOA',
    locale: 'pt-AO',
  },
  {
    name: 'Argentina',
    value: 'AR',
    category: 'Americas',
    country: 'Argentina',
    currency: 'ARS',
    locale: 'es-AR',
  },
  {
    name: 'Australia',
    value: 'AU',
    category: 'Oceania',
    country: 'Australia',
    currency: 'AUD',
    locale: 'en-AU',
  },
  {
    name: 'Austria',
    value: 'AT',
    category: 'Europe',
    country: 'Austria',
    currency: 'EUR',
    locale: 'de-AT',
  },
  {
    name: 'Bangladesh',
    value: 'BD',
    category: 'Asia',
    country: 'Bangladesh',
    currency: 'BDT',
    locale: 'bn-BD',
  },
  {
    name: 'Belgium',
    value: 'BE',
    category: 'Europe',
    country: 'Belgium',
    currency: 'EUR',
    locale: 'nl-BE',
  },
  {
    name: 'Brazil',
    value: 'BR',
    category: 'Americas',
    country: 'Brazil',
    currency: 'BRL',
    locale: 'pt-BR',
  },
  {
    name: 'Canada',
    value: 'CA',
    category: 'Americas',
    country: 'Canada',
    currency: 'CAD',
    locale: 'en-CA',
  },
  {
    name: 'Chile',
    value: 'CL',
    category: 'Americas',
    country: 'Chile',
    currency: 'CLP',
    locale: 'es-CL',
  },
  {
    name: 'China',
    value: 'CN',
    category: 'Asia',
    country: 'China',
    currency: 'CNY',
    locale: 'zh-CN',
  },
  {
    name: 'Colombia',
    value: 'CO',
    category: 'Americas',
    country: 'Colombia',
    currency: 'COP',
    locale: 'es-CO',
  },
  {
    name: 'Czech Republic',
    value: 'CZ',
    category: 'Europe',
    country: 'Czech Republic',
    currency: 'CZK',
    locale: 'cs-CZ',
  },
  {
    name: 'Denmark',
    value: 'DK',
    category: 'Europe',
    country: 'Denmark',
    currency: 'DKK',
    locale: 'da-DK',
  },
  {
    name: 'Egypt',
    value: 'EG',
    category: 'Africa',
    country: 'Egypt',
    currency: 'EGP',
    locale: 'ar-EG',
  },
  {
    name: 'Ethiopia',
    value: 'ET',
    category: 'Africa',
    country: 'Ethiopia',
    currency: 'ETB',
    locale: 'am-ET',
  },
  {
    name: 'Finland',
    value: 'FI',
    category: 'Europe',
    country: 'Finland',
    currency: 'EUR',
    locale: 'fi-FI',
  },
  {
    name: 'France',
    value: 'FR',
    category: 'Europe',
    country: 'France',
    currency: 'EUR',
    locale: 'fr-FR',
  },
  {
    name: 'Germany',
    value: 'DE',
    category: 'Europe',
    country: 'Germany',
    currency: 'EUR',
    locale: 'de-DE',
  },
  {
    name: 'Ghana',
    value: 'GH',
    category: 'Africa',
    country: 'Ghana',
    currency: 'GHS',
    locale: 'en-GH',
  },
  {
    name: 'India',
    value: 'IN',
    category: 'Asia',
    country: 'India',
    currency: 'INR',
    locale: 'hi-IN',
  },
  {
    name: 'Indonesia',
    value: 'ID',
    category: 'Asia',
    country: 'Indonesia',
    currency: 'IDR',
    locale: 'id-ID',
  },
  {
    name: 'Italy',
    value: 'IT',
    category: 'Europe',
    country: 'Italy',
    currency: 'EUR',
    locale: 'it-IT',
  },
  {
    name: 'Japan',
    value: 'JP',
    category: 'Asia',
    country: 'Japan',
    currency: 'JPY',
    locale: 'ja-JP',
  },
  {
    name: 'Kenya',
    value: 'KE',
    category: 'Africa',
    country: 'Kenya',
    currency: 'KES',
    locale: 'en-KE',
  },
  {
    name: 'Mexico',
    value: 'MX',
    category: 'Americas',
    country: 'Mexico',
    currency: 'MXN',
    locale: 'es-MX',
  },
  {
    name: 'Netherlands',
    value: 'NL',
    category: 'Europe',
    country: 'Netherlands',
    currency: 'EUR',
    locale: 'nl-NL',
  },
  {
    name: 'New Zealand',
    value: 'NZ',
    category: 'Oceania',
    country: 'New Zealand',
    currency: 'NZD',
    locale: 'en-NZ',
  },
  {
    name: 'Nigeria',
    value: 'NG',
    category: 'Africa',
    country: 'Nigeria',
    currency: 'NGN',
    locale: 'en-NG',
  },
  {
    name: 'Norway',
    value: 'NO',
    category: 'Europe',
    country: 'Norway',
    currency: 'NOK',
    locale: 'no-NO',
  },
  {
    name: 'Pakistan',
    value: 'PK',
    category: 'Asia',
    country: 'Pakistan',
    currency: 'PKR',
    locale: 'ur-PK',
  },
  {
    name: 'Philippines',
    value: 'PH',
    category: 'Asia',
    country: 'Philippines',
    currency: 'PHP',
    locale: 'fil-PH',
  },
  {
    name: 'Poland',
    value: 'PL',
    category: 'Europe',
    country: 'Poland',
    currency: 'PLN',
    locale: 'pl-PL',
  },
  {
    name: 'Russia',
    value: 'RU',
    category: 'Europe/Asia',
    country: 'Russia',
    currency: 'RUB',
    locale: 'ru-RU',
  },
  {
    name: 'Saudi Arabia',
    value: 'SA',
    category: 'Middle East',
    country: 'Saudi Arabia',
    currency: 'SAR',
    locale: 'ar-SA',
  },
  {
    name: 'South Africa',
    value: 'ZA',
    category: 'Africa',
    country: 'South Africa',
    currency: 'ZAR',
    locale: 'en-ZA',
  },
  {
    name: 'South Korea',
    value: 'KR',
    category: 'Asia',
    country: 'South Korea',
    currency: 'KRW',
    locale: 'ko-KR',
  },
  {
    name: 'Spain',
    value: 'ES',
    category: 'Europe',
    country: 'Spain',
    currency: 'EUR',
    locale: 'es-ES',
  },
  {
    name: 'Sweden',
    value: 'SE',
    category: 'Europe',
    country: 'Sweden',
    currency: 'SEK',
    locale: 'sv-SE',
  },
  {
    name: 'Switzerland',
    value: 'CH',
    category: 'Europe',
    country: 'Switzerland',
    currency: 'CHF',
    locale: 'de-CH',
  },
  {
    name: 'Thailand',
    value: 'TH',
    category: 'Asia',
    country: 'Thailand',
    currency: 'THB',
    locale: 'th-TH',
  },
  {
    name: 'Turkey',
    value: 'TR',
    category: 'Europe/Asia',
    country: 'Turkey',
    currency: 'TRY',
    locale: 'tr-TR',
  },
  {
    name: 'United Arab Emirates',
    value: 'AE',
    category: 'Middle East',
    country: 'United Arab Emirates',
    currency: 'AED',
    locale: 'ar-AE',
  },
  {
    name: 'United Kingdom',
    value: 'GB',
    category: 'Europe',
    country: 'United Kingdom',
    currency: 'GBP',
    locale: 'en-GB',
  },
  {
    name: 'United States',
    value: 'US',
    category: 'Americas',
    country: 'United States',
    currency: 'USD',
    locale: 'en-US',
  },
  {
    name: 'Vietnam',
    value: 'VN',
    category: 'Asia',
    country: 'Vietnam',
    currency: 'VND',
    locale: 'vi-VN',
  },
  {
    name: 'Zimbabwe',
    value: 'ZW',
    category: 'Africa',
    country: 'Zimbabwe',
    currency: 'ZWL',
    locale: 'en-ZW',
  },
];
