import type { Metadata } from 'next';
import { RootLayoutComp } from '@/components/layout/root-layout';
import { Geist, Geist_Mono, Inter, Arima } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { dir } from 'i18next';
import { initServerI18next, getT, getResources } from 'next-i18next/server';
import { I18nProvider } from 'next-i18next/client';
import i18nConfig from '../i18n.config';
import { Toaster } from '@/components/ui/sonner';

initServerI18next(i18nConfig);

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});

const arima = Arima({
  subsets: ['latin'],
  variable: '--font-arima',
});

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const { i18n } = await getT();
  const lng = i18n.resolvedLanguage ?? i18n.language ?? 'en';
  const resources = getResources(i18n);
  return (
    <html
      lang={lng}
      // dir={dir(
      //   lng,
      // )}
      className={cn(
        'h-full',
        'antialiased',
        geistSans.variable,
        geistMono.variable,
        arima.variable,
        'font-sans',
        inter.variable
      )}
    >
      <body className="min-h-full flex flex-col">
        {' '}
        <RootLayoutComp>
          <I18nProvider language={lng} resources={resources}>
            {children}
            <Toaster richColors position="top-center" />
          </I18nProvider>
        </RootLayoutComp>
      </body>
    </html>
  );
}
