import { STORE_DETAILS } from '@/constants/store-details';
import { Metadata } from 'next';
import React from 'react';
export const metadata: Metadata = {
  title: `Orders - ${STORE_DETAILS.name}`,
  description: 'Generated by create next app',
};

export default function OrderLayout({ children }: { children: React.ReactNode }) {
  return <section>{children}</section>;
}
